version: "2"

services:
  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${RETHINKDB_PASSWORD}
      POSTGRES_DB: airtable
    ports:
      - "5432:5432"
    networks:
      - sai
    volumes:
      - rethink-data:/data
  app:
    build: .
    container_name: app
    ports:
      - "3000:5555"
    networks:
      - sai
    links:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/airtable?schema=public
    depends_on:
      - db
networks:
  sai:
    driver: bridge

volumes:
  rethink-data:
    driver: local
