version: "2"

services:
  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${RETHINKDB_PASSWORD}
      POSTGRES_DB: airtable
    ports:
      - "5432:5432"
    networks:
      - sai
    volumes:
      - rethink-data:/data
networks:
  sai:
    driver: bridge

volumes:
  rethink-data:
    driver: local
